version: '3.6'
services:
  db:
    image: postgres:10
    network_mode: bridge
    container_name: demo-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: demo
      POSTGRES_DB: demo
    ports:
      #- 5433:5432
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    expose: 
      - 5433
    restart: unless-stopped
  springbootapp:
    image: yahiadev/kubernetes-spring-postgres-demo:0.8
    network_mode: bridge
    container_name: springbootapp
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db