server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/demo
    username: demo
    password: password

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults : false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
