apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springbootapp
  name: spring-boot-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    nodePort: 30007
  selector:
    app: springbootapp
  type: LoadBalancer
status:
  loadBalancer: {}
